all: \
  $(addsuffix .cht, $(basename $(wildcard iso/chart/*.json)))

iso/chart/%.cht: iso/chart/%.json
	tools/funkinchtpak/funkinchtpak $@ $<

# Rule to clean all .cht files
clean:
	echo "Cleaning .cht files:"
	find iso -type f \( -name "*.cht" \) -print -delete
